export const library = [

    {
        "isbn": '1838850996',
        "title": 'LiveWired',
        "author": 'David Eagleman',
        "type": 'Neuroscience',
        "image": 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXnCy6M3hW3AqdLZMfI11gIhqUTqzDjjrpY2RprO16xF3_8-L-isDCsdMjt1Wb3RIDNDI&usqp=CAU',
        "isNewPublished": true,
        "reviews": [],
        "description": "This book is not simply about what the brain is, but what it does. Covering decades of research to the present day, Livewired also presents new findings from Eagleman's own research, including new discoveries in synaesthesia, dreaming and wearable neurotech devices that revolutionise how we think about the senses.",
    },
    {
        isbn: '0316056286',
        title: 'Outliers',
        author: 'Malcolm Gladwell',
        type: 'Improvement',
        image: 'https://images-na.ssl-images-amazon.com/images/I/31ubkQ+t9dL._SX296_BO1,204,203,200_.jpg',
        isNewPublished: true,
        reviews: [],
        description: 'In this stunning New York Times best seller, Blink and The Tipping Point author Malcolm Gladwell takes us on an intellectual journey through the world of "outliers"?the best, brightest, most famous and most successful?learning that we pay too much attention to what successful people are like, and too little attention to where they are from.',
    },
    {
        isbn: '0061339202',
        title: 'Flow',
        author: 'Mihaly Csikszentmihalyi',
        type: 'Pyscology',
        image: 'https://media.s-bol.com/NVv549w8QKK/550x833.jpg',
        isNewPublished: true,
        reviews: [],
        description: "Csikszentmihalyi arrives at an insight that many of us can intuitively grasp, despite our insistent (and culturally supported) denial of this truth. That is, it is not what happens to us that determines our happiness, but the manner in which we make sense of that reality. . . . The manner in which Csikszentmihalyi integrates research on consciousness, personal psychology and spirituality is illuminating."

    },
    {
        isbn: '0571290906',
        title: 'Conquerors',
        author: 'Roger Crowley',
        type: 'History',
        image: 'https://images-na.ssl-images-amazon.com/images/I/51GUVgihGZL._SY344_BO1,204,203,200_QL70_ML2_.jpg',
        isNewPublished: true,
        reviews: [],
        description: "As remarkable as Columbus and the conquistador expeditions, the history of Portuguese exploration is now almost forgotten. But Portugal's navigators cracked the code of the Atlantic winds, launched the expedition of Vasco da Gama to India and beat the Spanish to the spice kingdoms of the East - then set about creating the first long-range maritime empire. In an astonishing blitz of thirty years, a handful of visionary and utterly ruthless empire builders, with few resources but breathtaking ambition, attempted to seize the Indian Ocean, destroy Islam and take control of world trade. Told with Roger Crowley's customary skill and verve, this is narrative history at its most vivid - an epic tale of navigation, trade and technology, money and religious zealotry, political diplomacy and espionage, sea battles and shipwrecks, endurance, courage and terrifying brutality. Drawing on extensive first-hand accounts, it brings to life the exploits of an extraordinary band of conquerors - men such as Afonso de Albuquerque, the first European since Alexander the Great to found an Asian empire - who set in motion five hundred years of European colonisation and unleashed the forces of globalisation.",

    },
    {
        isbn: '1401308503',
        title: '1453',
        author: 'Roger Crowley',
        type: 'History',
        image: 'https://m.media-amazon.com/images/I/51EMDSBEZXL._AC_UL480_FMwebp_QL65_.jpg',
        isNewPublished: true,
        reviews: [],
        description: "The fall of Constantinople in 1453 signaled a shift in history, and the end of the Byzantium Empire. Roger Crowley's readable and comprehensive account of the battle between Mehmed II, sultan of the Ottoman Empire, and Constantine XI, the 57th emperor of Byzantium, illuminates the period in history that was a precursor to the current jihad between the West and the Middle East.",
    },
    {
        isbn: '0141033576',
        title: 'Thinking Fast and Slow',
        author: 'Daniel Kahneman',
        type: 'Neuroscience',
        image: 'https://m.media-amazon.com/images/I/81-Q4oeHicL._AC_UL480_FMwebp_QL65_.jpg',
        isNewPublished: true,
        reviews: [],
        description: "Looks at the way our minds work, and how we make decisions. This book reveals how our minds are tripped up by error and prejudice (even when we think we are being logical), and gives you practical techniques for slower, smarter thinking. It enables you to make better decisions at work, at home, and in everything you do.",

    },
    {
        isbn: "0141988495",
        title: 'Talking to Strangers',
        author: 'Malcolm Gladwell',
        type: 'Sociology',
        image: 'https://media.s-bol.com/53gNK4XKEZpx/0Ygvo0V/515x840.jpg',
        isNewPublished: true,
        reviews: [],
        description: "The highly anticipated new book from Malcolm Gladwell, No.1 international bestselling author of The Tipping Point, Blink, Outliers, What the Dog Saw and David and Goliath. In July 2015, a young black woman named Sandra Bland was pulled over for a minor traffic violation in rural Texas. Minutes later she was arrested and jailed. Three days later, she committed suicide in her cell. What went wrong? Talking to Strangers is all about what happens when we encounter people we don't know, why it often goes awry, and what it says about us. How do we make sense of the unfamiliar? Why are we so bad at judging someone, reading a face, or detecting a lie? Why do we so often fail to 'get' other people? Through a series of puzzles, encounters and misunderstandings, from little-known stories to infamous legal cases, Gladwell takes us on a journey through the unexpected. You will read about the spy who spent years undetected at the highest levels of the Pentagon, the man who saw through the fraudster Bernie Madoff, the suicide of the poet Sylvia Plath and the false conviction of Amanda Knox. You will discover that strangers are never simple. No one shows us who we are like Malcolm Gladwell. Here he sets out to understand why we act the way we do, and how we all might know a little more about those we don't.",
    },
    {
        isbn: '0800736370',
        title: 'Until Leaves Fall in Paris',
        author: 'Sarah Sundin',
        type: 'Sociology',
        image: 'https://m.media-amazon.com/images/I/61C8gXTqgIL._AC_UL480_FMwebp_QL65_.jpg',
        isNewPublished: true,
        reviews: [],
        description: 'As the Nazis march toward Paris in 1940, American ballerina Lucie Girard buys her favorite English-language bookstore to allow the Jewish owners to escape. Lucie struggles to run Green Leaf Books due to oppressive German laws and harsh conditions, but she finds a way to aid the resistance by passing secret messages between the pages of her books.',
    },
    {
        isbn: "1398803537",
        title: 'The Nazis and the Occult',
        author: 'Paul Roland',
        type: 'History',
        image: 'https://images-na.ssl-images-amazon.com/images/I/41XGiqwGMtL._SX324_BO1,204,203,200_.jpg',
        isNewPublished: true,
        reviews: [],
        description: 'The book is extremely readable and accessible while still keeping fresh and interesting and giving an in-depth look to the myriad factors that led to the creation of Nazi Germany, from economic to psychological.'
    },
    {
        isbn: '0141983769',
        title: 'Why We Sleep',
        author: 'Matthew Walker',
        type: 'Neuroscience',
        image: 'https://m.media-amazon.com/images/I/71k+6XWQelL._AC_UL480_FMwebp_QL65_.jpg',
        isNewPublished: true,
        reviews: [],
        description: 'Using science to explain why sleep is so essential, the author is a neuroscientist and sleep expert who has spent nearly 20 years studying the effects of sleep on our brains and bodies. Reveals the links between sleep and the treatment of a range of health issues including Alzheimer',
    },
    {
        isbn: '0670921602',
        title: 'The Lean Startup',
        author: 'Eric Ries',
        type: 'Business',
        image: 'https://images-na.ssl-images-amazon.com/images/I/51aEhyjQGrL._SX316_BO1,204,203,200_.jpg',
        isNewPublished: true,
        reviews: [],
        description: "Most new businesses fail. But most of those failures are preventable. This title offers a fresh approach to business that's being adopted around the world. It describes learning what your customers really want, testing your vision continuously, and adapting and adjusting before it's too late.",
    },
    {
        isbn: '9780091906818',
        title: 'How to Win Friends and Influence People',
        author: 'Dale Carnegie',
        type: 'Human Resources',
        image: 'https://images-na.ssl-images-amazon.com/images/I/51EV3zDJz2L._SX318_BO1,204,203,200_.jpg',
        isNewPublished: true,
        reviews: [],
        description: 'Offering practical advice and techniques, this book helps you to learn how to get out of a mental rut and make life more rewarding. It supports you to turn your relationships around and improve your interactions with everyone in your life.',
    },
]